@baseURL = http://localhost:3333
@userId = {{create_user.response.body.user_id}}
@taskId = {{create_task.response.body.task.id}}

# @name create_user
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "Eduardo Rodrigues",
  "email": "eduardo1@example.com",
  "password": "123456",
  "cnpj": "12345678",
  "phone": "teste"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "eduardo1@example.com",
  "password": "123456"
}

###

# @name update_user
PUT {{baseURL}}/users/f48afc3e-672a-4915-8a40-6379e145e6be
Content-Type: application/json

{
  "data": {
    "name": "Eduardo Henrique Rodrigues",
    "companyName": "Rodrigues Caçamba"
  }
}

### List Users
GET {{baseURL}}/users
Content-Type: application/json

### Get a User
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json

### Remove a User
DELETE  {{baseURL}}/users/{{userId}}
Content-Type: application/json


### TASKS
# @name create_task
POST {{baseURL}}/tasks
Content-Type: application/json

{
  "buckets": 1,
  "userId": "aaba2f65-5e5a-4c38-ae43-b6b94eb5a14d"
}

###
# @name edit_tasks
PUT {{baseURL}}/tasks/a40778b4-8783-4755-8d99-5e52775ea3fd
Content-Type: application/json

{
  "status": "CLOSED"
}

###
# @name list_tasks
GET {{baseURL}}/tasks/list/aaba2f65-5e5a-4c38-ae43-b6b94eb5a14d?page=1

###
# @name get_task
GET {{baseURL}}/tasks/{{taskId}}

###
# @name delete_task
DELETE {{baseURL}}/tasks/046bec32-1827-47f2-a1b3-17095d4f1c82
