@baseURL = http://localhost:3333
@userId = {{create_user.response.body.user_id}}
@taskId = {{create_task.response.body.task.id}}

# @name create_user
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "Eduardo Rodrigues",
  "email": "eduardo2@example.com",
  "password": "123456",
  "cnpj": "123456781",
  "phone": "teste"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "eduardo@example.com",
  "password": "123456"
}

###

# @name update_user
PUT {{baseURL}}/users/8b47452f-fe12-4f0c-b263-ea56abc2372c
Content-Type: application/json

{
  "name": "Eduardo Henrique Rodrigues",
  "companyName": "Rodrigues Caçamba"
}

### List Users
GET {{baseURL}}/users
Content-Type: application/json

### Get a User
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json

### Remove a User
DELETE  {{baseURL}}/users/{{userId}}
Content-Type: application/json


### TASKS
# @name create_task
POST {{baseURL}}/tasks
Content-Type: application/json

{
  "buckets": 1,
  "userId": "71ace94c-2e66-4fa8-b295-a61fdb36d535"
}

###
# @name edit_tasks
PUT {{baseURL}}/tasks/clvq0yw6y0003tlqij81wfumz
Content-Type: application/json

{
  "status": "CLOSED"
}

###
# @name list_tasks
GET {{baseURL}}/tasks/list/29dd22b2-e2b1-46b7-8f6a-ea46eb2acfc3?page=1

###
# @name get_task
GET {{baseURL}}/tasks/{{taskId}}

###
# @name delete_task
DELETE {{baseURL}}/tasks/{{taskId}}
